### PR TITLE
Fix vector libspecs

### PR DESCRIPTION
**Pull request by athos**
This PR makes it possible to use lists and vectors totally interchangeably to represent libspecs in the `ns` macro.

The current implementation handles libspecs represented with a list  and ones represented with a vector in different ways. Especially, only list libspecs are allowed to have prefix lists. So, for example, it can deal with something like:
```clojure
(ns example.foo
  (:require (example [bar :as bar]
                     [baz :as baz])))
          ; ^ a list libspec
```

but not:
```clojure
(ns example.foo
  (:require [example [bar :as bar]
                     [baz :as baz]]))
          ; ^ a vector libspec
```

A lot of Clojure libraries out there are using lists and vectors interchangeably in their `ns` declarations. It would make more people (including me) happy if ns-tracker could deal with forms like that :)

### CODE REVIEW

**Comment by athos** [comment]
Sorry, I wasn't aware some tests failed, but just fixed.

**Comment by weavejester** [comment]
Can you write some tests for this?

**Comment by athos** [comment]
Just added tests (along with it, I fixed a bug found on the way).

**Comment by weavejester** [comment]
Can you squash your commits down, and ensure that the commit summary line is under 70 characters?

**Comment by athos** [comment]
Done.

**Pull request merged**
